name: robo_mobile_bot
description: Mobile controller app for an MT5/Python trading bot
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
